### ISSUE TITLE
How do I turn off the transparency effect of the message box?

### ISSUE THREAD

**Issue by ldnazk** [YashjitPal/Arc-2.0#83]
As shown in the image, I believe I've already turned off the transparency effects in the settings, but the transparency of this notification box is still present.
<img width="1606" height="1480" alt="Image" src="https://github.com/user-attachments/assets/d6db5379-2cf9-4464-b461-26c892296351" />

<img width="2015" height="3110" alt="Image" src="https://github.com/user-attachments/assets/4b6f5c79-0812-4feb-b570-39e68130c59b" />

**Comment by Anber55** [comment]
Same problem

In addition, I would like to ask how to configure the color of the picture. Can it be configured using code? It is too difficult to configure manually. Thank you.

<img width="385" height="503" alt="Image" src="https://github.com/user-attachments/assets/d8df7f79-d436-4fd6-965c-f5433e66021c" />

**Comment by Comp-Tech-Guy** [comment]
@ldnazk We fixed that issue and have a new look for pref settings. So get the latest version, which will be 3.2.9 but you could see the difference when you see the pref, which will have a new look altogether like this below

<img width="961" height="1039" alt="Image" src="https://github.com/user-attachments/assets/d4433930-781d-498b-9259-2d46547ca8fb" />

**Comment by Talalahmed409** [comment]
@Comp-Tech-Guy updated to V3.2.9 but still having the same issue with right click having a completely transparent background

**Comment by GitDevEnv** [comment]
> I found a new problem: Press Command+l, click on the blank space when the search bar appears, and the URL in the sidebar will flash.
> 2025-12-21.14.04.25.online-video-cutter.com.mp4

Fixed
